### PR TITLE
Refactor internal logic and improve tests

### PR DESCRIPTION
**Pull request by sstok**
|Q            |A  |
|---          |---|
|Bug Fix?     |no |
|New Feature? |yes|
|BC Breaks?   |no |
|Deprecations?|no |
|Fixed Tickets| #1 #4  |
|License      |MIT|

TODO:
- [x] Tests to ensure the correct result
- [x] Test for MySQL as well (currently only pgsql and sqlite)
- [x] Tests for conversions (functional)

### CODE REVIEW

**Comment by sstok** [comment]
We hit a :bug: :warning: Its small one (missing space between NOT and LIKE), but this proofs why functional tests are needed.

```
Exception: [Doctrine\DBAL\Exception\SyntaxErrorException] An exception occurred while executing 'SELECT i.*, c.* FROM invoice AS i JOIN customer AS c ON (c.id = i.customer) WHERE (((c.name LIKE :customer_name_0 ESCAPE '\\' OR c.name LIKE :customer_name_1 ESCAPE '\\' OR c.name ~ :customer_name_2 OR c.name ~* :customer_name_3) AND (c.name NOTILIKE :customer_name_4 ESCAPE '\\')))' with params ["foo", "fo\\'o", "(foo|bar)", "(doctor|who)", "bar"]:
```

**Comment by sstok** [comment]
OK, I'm getting a bit irritated here by the fact that no almost database vendor honors the so-called official standard! :angry: :boom: 

MySQL doesn't allow to cast a value to INTEGER, because thats is called SIGNED [INTEGER].
SQLite does not automatically casts an quoted an integer to a real integer, so `u.age = 18` and `u.age = '18'` are not the same. Even when age is an INTEGER ITS NOT CASTED! WHAT THE HELL IS WRONG WITH THESE DEVELOPERS?! I need to add at least 5 checks to get this to work.

**Comment by cordoval** [comment]
oh no sorry! :older_man:

**Comment by sstok** [comment]
I'm doing so rewriting to fix this and reduce the complexity.

**Comment by sstok** [comment]
Hmm, the parameter binding is causing trouble #6 and I actually can't see why we would need this.
Using parameters is only recommended when you want to reuse the query with different values, but the SearchCondition where-clause never changes a single value, and even then the whole query needs to be re-evaluated so I think its better to always embed the values.

**Comment by sstok** [comment]
https://scrutinizer-ci.com/g/rollerworks/rollerworks-search-doctrine-dbal/inspections/f1ced7e0-72b4-43d1-81c4-7d1836e4fb50 Wow :+1: now thats what I call improvement :smile:

**Comment by sstok** [comment]
https://scrutinizer-ci.com/g/rollerworks/rollerworks-search-doctrine-dbal/inspections/418a0150-1bd1-4be4-94bf-9418e7796768 - score 8.46 This is amazing :scream: :satisfied: 2.4 quality increase and no more critical issues :+1:

**Comment by cordoval** [comment]
nice. Try more SOLID and it will keep going up

**Comment by sstok** [comment]
:sweat_smile: whoops I need to merge a PR in the core package before the tests can work.

**Comment by sstok** [comment]
Depends on https://github.com/rollerworks/RollerworksSearch/pull/60

**Comment by sstok** [comment]
Merged

**Pull request merged**
